const CFG=window.GT_CONFIG,API='https://sheets.googleapis.com/v4/spreadsheets';
const $=id=>document.getElementById(id),S={token:null,user:null,rows:[],view:'today',area:'',q:'',status:'',category:'',min:0,sort:'priority',timer:null};
const H=['リードID','企業名','都道府県','市区町村','郵便番号','住所','電話番号','業種カテゴリ','業種詳細','営業優先スコア','営業確度','営業ステータス','営業担当','訪問予定日','訪問順','最終対応日','次回対応日','次回アクション','最新結果','決裁者・担当者','訪問受付','問い合わせ先','主な取扱商材','想定物量','既存販路','営業メモ','情報源URL','登録日','更新日時','更新者'];
const statuses=['未着手','訪問予定','訪問済み','再訪予定','商談中','成約','見送り'],visitResults=['不在','受付NG','担当不在','担当接触','資料渡し','再訪依頼','商談化'],dealResults=['未設定','情報収集','見込み低','見込み中','見込み高','見積依頼','成約','失注'],actions=['初回訪問','再訪問','電話','メール','見積送付','社内確認','追客','クローズ'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),today=()=>new Date().toISOString().slice(0,10),now=()=>new Date().toISOString();
function ready(){return !CFG.googleClientId.startsWith('REPLACE_')}function sync(c,t){$('syncDot').className=c;$('syncText').textContent=t;$('syncTime').textContent=c==='ok'?new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}):'—'}function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function login(){if(!ready()){ $('loginError').textContent='Google OAuth Client IDの設定待ちです。';return}google.accounts.oauth2.initTokenClient({client_id:CFG.googleClientId,scope:'openid email profile https://www.googleapis.com/auth/spreadsheets',callback:async r=>{if(r.error)return $('loginError').textContent=r.error;S.token=r.access_token;await user();await load();$('login').classList.add('hidden');$('app').classList.remove('hidden');S.timer=setInterval(load,CFG.refreshSeconds*1000)}}).requestAccessToken({prompt:'consent'})}
async function user(){const r=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:`Bearer ${S.token}`}});S.user=await r.json();$('userName').textContent=S.user.name||S.user.email;$('userEmail').textContent=S.user.email;$('avatar').textContent=(S.user.name||S.user.email)[0]}
async function api(path,opt={}){const r=await fetch(`${API}/${CFG.spreadsheetId}/${path}`,{...opt,headers:{Authorization:`Bearer ${S.token}`,'Content-Type':'application/json'}});if(!r.ok)throw new Error((await r.json()).error?.message||'Google Sheetsとの通信に失敗しました');return r.json()}
async function load(){sync('busy','同期中');try{const d=await api(`values/${encodeURIComponent(`'${CFG.masterSheet}'!A2:AD5000`)}`);S.rows=(d.values||[]).filter(a=>a[0]).map((a,i)=>{const r=Object.fromEntries(H.map((h,j)=>[h,a[j]??'']));r._row=i+2;return r});filters();render();sync('ok','同期済み')}catch(e){sync('','同期エラー');toast(e.message)}}
function filters(){if(!$('statusFilter').dataset.ready){$('statusFilter').innerHTML+=[...statuses].map(x=>`<option>${x}</option>`).join('');$('statusFilter').dataset.ready=1}$('categoryFilter').innerHTML='<option value="">すべての業種</option>'+[...new Set(S.rows.map(r=>r.業種カテゴリ))].sort().map(x=>`<option>${esc(x)}</option>`).join('');$('areaNav').innerHTML=[...new Set(S.rows.map(r=>r.都道府県))].map(p=>`<button class="area-btn" data-area="${p}">${p}<span>${S.rows.filter(r=>r.都道府県===p).length}</span></button>`).join('')}
const owner=r=>r.営業担当===S.user?.email||r.営業担当===S.user?.name;function list(){let x=S.rows.filter(r=>{if(S.view==='today'&&!(owner(r)&&r.訪問予定日===today()))return false;if(S.view==='mine'&&!(owner(r)&&['訪問予定','再訪予定'].includes(r.営業ステータス)))return false;if(S.view==='all'&&!['未着手','再訪予定'].includes(r.営業ステータス))return false;if(S.view==='appointments'&&!['商談中','成約'].includes(r.営業ステータス))return false;if(S.area&&r.都道府県!==S.area)return false;if(S.status&&r.営業ステータス!==S.status)return false;if(S.category&&r.業種カテゴリ!==S.category)return false;if(+r.営業優先スコア<S.min)return false;if(S.q&&![r.企業名,r.住所,r.電話番号,r.市区町村,r.営業メモ].join(' ').toLowerCase().includes(S.q.toLowerCase()))return false;return true});x.sort((a,b)=>S.view==='today'?(+a.訪問順||999)-(+b.訪問順||999):S.sort==='score'?+b.営業優先スコア-+a.営業優先スコア:S.sort==='updated'?String(b.更新日時).localeCompare(String(a.更新日時)):+b.営業優先スコア-+a.営業優先スコア);return x}
function render(){const x=list(),mineToday=S.rows.filter(r=>owner(r)&&r.訪問予定日===today()).length;$('todayBadge').textContent=mineToday;$('kToday').textContent=mineToday;$('kUntouched').textContent=S.rows.filter(r=>r.営業ステータス==='未着手').length;$('kAppointments').textContent=S.rows.filter(r=>r.営業ステータス==='訪問済み').length;$('kWon').textContent=S.rows.filter(r=>r.営業ステータス==='商談中').length;$('resultCount').textContent=`${x.length}件`;$('activeLabel').textContent=S.area?`｜${S.area}`:'';$('cards').innerHTML=x.slice(0,400).map(card).join('');$('empty').classList.toggle('hidden',x.length>0)}
function card(r){return `<article class="lead" data-id="${esc(r.リードID)}"><div class="score ${+r.営業優先スコア>=70?'high':''}">${r.営業優先スコア}</div><div><h3>${esc(r.企業名)}</h3><div class="meta">${esc(r.業種カテゴリ)} ・ ${esc(r.都道府県)} ${esc(r.市区町村)} ・ ${esc(r.電話番号)}</div></div><div><span class="field-label">営業ステータス</span><span class="tag ${r.営業ステータス==='商談中'?'amber':''}">${esc(r.営業ステータス)}</span></div><div><span class="field-label">営業担当</span><span class="tag">${esc(r.営業担当||'未割当')}</span></div><div><span class="field-label">訪問予定</span><span class="date">${esc(r.訪問予定日||'未設定')}${r.訪問順?` / ${r.訪問順}番`:''}</span></div><div class="arrow">›</div></article>`}
function open(r){const planning=['未着手','再訪予定'].includes(r.営業ステータス);$('drawerContent').innerHTML=`<div class="detail-head"><p class="eyebrow">${esc(r.リードID)} / ${esc(r.都道府県)}</p><h2>${esc(r.企業名)}</h2><span class="tag green">${r.営業優先スコア}点・${esc(r.業種カテゴリ)}</span></div><div class="detail-grid"><div><small>電話</small><a href="tel:${esc(r.電話番号)}">${esc(r.電話番号)}</a></div><div><small>地図</small><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.住所)}">Googleマップで開く</a></div><div><small>住所</small>${esc(r.住所)}</div><div><small>現在の状態</small>${esc(r.営業ステータス)}</div></div>${planning?planForm(r):resultForm(r)}`;$('drawer').classList.remove('hidden');$(planning?'savePlan':'saveResult').onclick=()=>planning?savePlan(r):saveResult(r)}
function planForm(r){return `<h3>訪問先に登録</h3><div class="edit-box"><label>訪問予定日</label><input id="pDate" type="date" value="${today()}"></div><div class="edit-box"><label>訪問順</label><input id="pOrder" type="number" min="1" value="1"></div><div class="edit-box"><label>事前メモ</label><textarea id="pMemo">${esc(r.営業メモ)}</textarea></div><button id="savePlan" class="primary save">自分の訪問予定へ追加</button>`}
function resultForm(r){return `<h3>訪問・商談結果を登録</h3><div class="edit-box"><label>活動種別</label><select id="rType"><option>訪問</option><option>商談</option><option>電話</option><option>メール</option></select></div><div class="edit-box"><label>訪問結果</label><select id="rVisit">${visitResults.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="edit-box"><label>商談結果</label><select id="rDeal">${dealResults.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="edit-box"><label>更新後ステータス</label><select id="rStatus">${statuses.map(x=>`<option ${x===r.営業ステータス?'selected':''}>${x}</option>`).join('')}</select></div><div class="edit-box"><label>次回対応日</label><input id="rNext" type="date"></div><div class="edit-box"><label>次回アクション</label><select id="rAction">${actions.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="edit-box"><label>活動メモ</label><textarea id="rMemo" placeholder="会話内容、物量、決裁者、次回の約束など"></textarea></div><button id="saveResult" class="primary save">結果を登録して履歴に残す</button>`}
async function savePlan(r){const date=$('pDate').value,order=$('pOrder').value,memo=$('pMemo').value;if(!date)return toast('訪問予定日を入力してください');sync('busy','保存中');try{await update([{range:`'${CFG.masterSheet}'!L${r._row}:O${r._row}`,values:[['訪問予定',S.user.email,date,order]]},{range:`'${CFG.masterSheet}'!Z${r._row}:AD${r._row}`,values:[[memo,r.情報源URL,r.登録日,now(),S.user.email]]}]);await appendLog(r,'訪問予定登録','予定登録','訪問予定','', '','',memo);$('drawer').classList.add('hidden');await load();toast('訪問予定へ追加しました')}catch(e){toast(e.message)}}
async function saveResult(r){const type=$('rType').value,vr=$('rVisit').value,dr=$('rDeal').value,st=$('rStatus').value,next=$('rNext').value,act=$('rAction').value,memo=$('rMemo').value,result=`${vr} / ${dr}`;sync('busy','保存中');try{await update([{range:`'${CFG.masterSheet}'!L${r._row}:S${r._row}`,values:[[st,S.user.email,r.訪問予定日,r.訪問順,today(),next,act,result]]},{range:`'${CFG.masterSheet}'!Z${r._row}:AD${r._row}`,values:[[[r.営業メモ,memo].filter(Boolean).join('\n'),r.情報源URL,r.登録日,now(),S.user.email]]}]);await appendLog(r,type,result,st,next,act,dr,memo);$('drawer').classList.add('hidden');await load();toast('結果を登録しました')}catch(e){toast(e.message)}}
async function update(data){return api('values:batchUpdate',{method:'POST',body:JSON.stringify({valueInputOption:'USER_ENTERED',data})})}async function appendLog(r,type,result,newStatus,next,act,deal,memo){const id=`ACT-${Date.now()}`,vals=[id,now(),S.user.name,S.user.email,r.リードID,r.企業名,type,result,r.営業ステータス,newStatus,next,act,'','',memo];return api(`values/${encodeURIComponent(`'${CFG.activitySheet}'!A:O`)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,{method:'POST',body:JSON.stringify({values:[vals]})})}
document.addEventListener('click',e=>{const n=e.target.closest('[data-view]');if(n){S.view=n.dataset.view;S.area='';document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===n));const m={today:['TODAY ROUTE','今日の訪問','訪問順に並べて、現地で結果を登録'],mine:['MY PLAN','自分の訪問予定','今後予定している訪問先'],all:['LEAD SEARCH','行き先を探す','エリアと優先度から訪問先を選択'],appointments:['DEALS','商談管理','商談中・成約案件を確認']} ;[$('viewEyebrow').textContent,$('viewTitle').textContent,$('viewDesc').textContent]=m[S.view];render()}const a=e.target.closest('[data-area]');if(a){S.view='all';S.area=a.dataset.area;$('viewTitle').textContent=`${S.area}で行き先を探す`;render()}const l=e.target.closest('.lead');if(l)open(S.rows.find(r=>r.リードID===l.dataset.id));if(e.target.matches('[data-close]'))$('drawer').classList.add('hidden')});
$('loginBtn').onclick=login;$('logout').onclick=()=>location.reload();$('refresh').onclick=load;$('search').oninput=e=>{S.q=e.target.value;render()};$('statusFilter').onchange=e=>{S.status=e.target.value;render()};$('categoryFilter').onchange=e=>{S.category=e.target.value;render()};$('scoreFilter').onchange=e=>{S.min=+e.target.value;render()};$('sort').onchange=e=>{S.sort=e.target.value;render()};$('clear').onclick=()=>{S.q=S.status=S.category='';S.min=0;$('search').value='';$('statusFilter').value=$('categoryFilter').value='';$('scoreFilter').value='0';render()};
if(['127.0.0.1','localhost'].includes(location.hostname)&&new URLSearchParams(location.search).has('demo')){S.user={name:'FS担当者',email:'fs@example.com'};S.rows=[['GT-1','サンプルリユース','東京都','江戸川区',82,'訪問予定','fs@example.com',today(),1],['GT-2','遺品整理サンプル','千葉県','船橋市',76,'未着手','未割当','',0],['GT-3','北関東買取店','埼玉県','さいたま市',71,'商談中','fs@example.com','',0]].map((x,i)=>Object.assign(Object.fromEntries(H.map(h=>[h,''])),{リードID:x[0],企業名:x[1],都道府県:x[2],市区町村:x[3],営業優先スコア:x[4],営業ステータス:x[5],営業担当:x[6],訪問予定日:x[7],訪問順:x[8],業種カテゴリ:'リサイクルショップ',電話番号:'03-0000-0000',住所:`${x[2]}${x[3]}サンプル住所`,_row:i+2}));$('userName').textContent=S.user.name;$('userEmail').textContent=S.user.email;$('avatar').textContent='F';$('login').classList.add('hidden');$('app').classList.remove('hidden');filters();render();sync('ok','デモ表示')}

